default: &default
  adapter: postgis
  encoding: unicode
  database: postgres
  pool: 10
  timeout: 5000

development:
  <<: *default
  username: postgres.aaudfysknshptqfrxuyw
  password: vasanth1234geodata
  host: aws-0-ap-south-1.pooler.supabase.com
  port: 6543

production:
  <<: *default
  username: postgres.aaudfysknshptqfrxuyw
  password: vasanth1234geodata
  host: aws-0-ap-south-1.pooler.supabase.com
  port: 6543