default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  timeout: 5000
  prepared_statements: false

development:
  <<: *default
  url: postgresql://postgres.aaudfysknshptqfrxuyw:vasanth1234geodata@aws-0-ap-south-1.pooler.supabase.com:6543/postgres

production:
  <<: *default
  url: postgresql://postgres.aaudfysknshptqfrxuyw:vasanth1234geodata@aws-0-ap-south-1.pooler.supabase.com:6543/postgres