default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: geo_data_development

production:
  <<: *default
  database: geo_data_production